// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urkohegqcvirmzpciili.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVya29oZWdxY3Zpcm16cGNpaWxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NDMxNzMsImV4cCI6MjA2OTExOTE3M30.z5Q8FybU2bDde3iq6mM2siMvjB59PzdboFYcoBfTZDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});